sudo: required
services:
    - docker

deploy:
    provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    region: "us-east-2"
    app: "core-image"
    env: "CoreImage-env"
    bucket_name: "elasticbeanstalk-us-east-2-138086560928"
    bucket_path: "core-image"
    on:
    branch: master
